sudo: false
language: node_js
node_js:
  - "node"
before_install:
- npm install -g webpack
before_script:
- npm run build-tests
- testem launchers
script: npm run travis

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

